#!/usr/bin/env python3
"""
Golden Master Screen Comparison Tests for Pure3270.

Screen buffers are compared against previously captured references. Two categories:

1. **s3270-authoritative references** (from s3270 reference implementation):
   - `pub400_golden.bin` - Generated from `pub400_login_s3270.json` (s3270 v4.5ga5
     connected to pub400.com:23). ASCII text lines encoded to EBCDIC (CP037) via
     `tools/capture_s3270_golden.py --from-json`. This is ground truth for what
     a correct TN3270 parser should produce for the pub400.com login screen.

2. **Pure3270 self-reference baselines** (legacy, trace-derived):
   - `login.screen.bin`, `ibmlink.screen.bin`, `ft_dft.screen.bin`, `ft-crash.screen.bin`
   - Generated by pure3270 parsing the corresponding `.trc` files. These detect
     pure3270 regressions (same trace → same screen) but do NOT verify correctness
     against s3270 since the traces themselves come from c3270/wc3270/s3270.
   - `ft_dft.trc` IS from s3270 (v4.2pre1 to 10.0.0.190:3270), but no s3270 golden
     was available at time of writing. The trace is ground truth; the .screen.bin
     is pure3270's interpretation.
   - `login.trc` is from c3270 to localhost:4001 (mock/test server), NOT pub400.com.
   - `ft-crash.trc` is from wc3270 (Windows c3270).
   - `ibmlink.trc` origin unknown (from c3270 family).

For new test screens: capture via `tools/capture_s3270_golden.py --host <host> --port 23`
using live s3270 ReadBuffer, or `--from-json` if an s3270 JSON reference exists.
"""

import logging
import re
import sys
from pathlib import Path

import pytest

# Silence DEBUG logging from the parser
logging.getLogger("pure3270.protocol.data_stream").setLevel(logging.WARNING)
logging.getLogger("pure3270.emulation.screen_buffer").setLevel(logging.WARNING)

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from pure3270.emulation.screen_buffer import ScreenBuffer
from pure3270.protocol.data_stream import DataStreamParser
from pure3270.protocol.utils import IAC, TN3270_DATA

TRACE_DIR = Path(__file__).parent / "data" / "traces"
SCREEN_DIR = Path(__file__).parent / "data" / "screens"


def parse_trace_to_buffer(trace_path: str) -> ScreenBuffer:
    """Parse a .trc file and return the resulting ScreenBuffer."""
    with open(trace_path, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()

    raw_data = b""
    for line in lines:
        line = line.strip()
        recv_match = re.match(r"<\s+0x\w+\s+([0-9a-fA-F\s]+)$", line)
        if recv_match:
            hex_data = recv_match.group(1).replace(" ", "")
            try:
                data = bytes.fromhex(hex_data)
                if data and data[0] != IAC:
                    raw_data += data
            except ValueError:
                pass

    screen = ScreenBuffer(24, 80)
    parser = DataStreamParser(screen)
    parser.parse(raw_data, TN3270_DATA)
    return screen


def diff_screen_buffers(actual: bytes, expected: bytes) -> list[str]:
    """
    Compare two screen buffers byte-by-byte and return list of differences.

    Each difference is a string like "row=3 col=12: expected=0x41 actual=0x42".
    """
    diffs = []
    for i in range(len(expected)):
        if actual[i] != expected[i]:
            row = i // 80
            col = i % 80
            diffs.append(
                f"row={row} col={col}: expected=0x{expected[i]:02x} actual=0x{actual[i]:02x}"
            )
    return diffs


class TestPub400GoldenScreen:
    """
    Compare pub400.com screen against s3270-authoritative golden reference.

    Source: s3270 v4.5ga5 connected to pub400.com:23, captured as JSON text lines,
    then encoded to EBCDIC (CP037) via `capture_s3270_golden.py --from-json`.

    This is the ONLY test that verifies pure3270 against the reference implementation
    (s3270). All other .screen.bin tests are pure3270 self-references.
    """

    @pytest.fixture(scope="class")
    def pub400_golden(self) -> bytes:
        """Load the s3270-authoritative pub400.com golden reference."""
        golden_path = SCREEN_DIR / "pub400_golden.bin"
        if not golden_path.exists():
            pytest.skip(
                "pub400_golden.bin not found (generate with capture_s3270_golden.py)"
            )
        with open(golden_path, "rb") as f:
            data = f.read()
        assert len(data) == 1920, f"pub400_golden.bin wrong size: {len(data)}"
        return data

    @pytest.fixture(scope="class")
    def pub400_trc_screen(self):
        """Parse the pub400.trc trace file (if it exists) for live-comparison tests."""
        trc_path = TRACE_DIR / "pub400.trc"
        if not trc_path.exists():
            pytest.skip("pub400.trc not found")
        screen = parse_trace_to_buffer(str(trc_path))
        return bytes(screen.buffer)

    def test_pub400_golden_exists(self, pub400_golden):
        """Verify the golden reference file is properly formed EBCDIC."""
        from pure3270.emulation.ebcdic import EBCDICCodec

        codec = EBCDICCodec()
        dec, _ = codec.decode(pub400_golden[:80])
        assert (
            "Welcome to PUB400.COM" in dec
        ), f"Golden row 0 missing expected text: {dec!r}"
        assert (
            pub400_golden[0] == 0x40
        ), "Golden first byte should be EBCDIC space (0x40)"

    def test_pub400_trc_matches_golden(self, pub400_golden, pub400_trc_screen):
        """Parse pub400.trc and compare byte-by-byte against s3270 golden."""
        diffs = diff_screen_buffers(pub400_trc_screen, pub400_golden)
        if diffs:
            diff_summary = "\n".join(diffs[:10])
            if len(diffs) > 10:
                diff_summary += f"\n... and {len(diffs) - 10} more differences"
            pytest.fail(
                f"pub400.trc mismatch ({len(diffs)} differences):\n{diff_summary}"
            )


class TestScreenStabilityAcrossRuns:
    """Validate that parsing the same trace file produces identical results every time."""

    @pytest.mark.parametrize(
        "trace_name",
        [
            "login.trc",
            "ibmlink.trc",
            "ft_dft.trc",
            "ft-crash.trc",
        ],
    )
    def test_deterministic_parsing(self, trace_name):
        """Parsing the same trace file twice should produce identical screens."""
        trace_path = TRACE_DIR / trace_name
        if not trace_path.exists():
            pytest.skip(f"Trace file not found: {trace_name}")

        screen1 = parse_trace_to_buffer(str(trace_path))
        screen2 = parse_trace_to_buffer(str(trace_path))

        buffer1 = bytes(screen1.buffer)
        buffer2 = bytes(screen2.buffer)

        assert (
            buffer1 == buffer2
        ), f"Non-deterministic parsing of {trace_name}: screens differ between runs"

        # Also check cursor position
        assert (
            screen1.cursor_row == screen2.cursor_row
        ), "Cursor row differs between runs"
        assert (
            screen1.cursor_col == screen2.cursor_col
        ), "Cursor col differs between runs"


class TestPure3270RegressionDetection:
    """
    Detect pure3270 regressions by comparing parsed screens against pure3270 baselines.

    WARNING: These golden files were generated by pure3270 itself (not s3270).
    They are useful for catching regressions in pure3270's parsing behavior,
    but do NOT verify correctness against the s3270 reference implementation.

    Trace origins:
    - login.trc: c3270 v4.3pre10 → localhost:4001 (mock/test server)
    - ft_dft.trc: s3270 v4.2pre1 → 10.0.0.190:3270 (actual host, but no s3270 golden available)
    - ft-crash.trc: wc3270 (Windows c3270) → ? (unknown host)
    - ibmlink.trc: c3270 family → ? (unknown host)
    """

    @pytest.mark.parametrize(
        "trace_name",
        [
            "login.trc",
            "ibmlink.trc",
            "ft_dft.trc",
            "ft-crash.trc",
        ],
    )
    def test_screen_matches_pure3270_baseline(self, trace_name):
        """Parse trace and compare against pure3270-generated baseline."""
        trace_path = TRACE_DIR / trace_name
        golden_path = SCREEN_DIR / trace_name.replace(".trc", ".screen.bin")

        if not trace_path.exists():
            pytest.skip(f"Trace file not found: {trace_name}")
        if not golden_path.exists():
            pytest.skip(f"Baseline reference not found: {golden_path.name}")

        # Parse trace to get actual screen
        actual_screen = parse_trace_to_buffer(str(trace_path))
        actual_buffer = bytes(actual_screen.buffer)

        # Load baseline reference
        with open(golden_path, "rb") as f:
            expected_buffer = f.read()

        assert len(actual_buffer) == len(
            expected_buffer
        ), f"Buffer length mismatch: {len(actual_buffer)} vs {len(expected_buffer)}"
        assert (
            len(expected_buffer) == 24 * 80
        ), f"Baseline has wrong size: {len(expected_buffer)} (expected 1920)"

        # Byte-by-byte comparison
        diffs = diff_screen_buffers(actual_buffer, expected_buffer)

        if diffs:
            diff_summary = "\n".join(diffs[:10])
            if len(diffs) > 10:
                diff_summary += f"\n... and {len(diffs) - 10} more differences"

            pytest.fail(
                f"Screen buffer regression for {trace_name} ({len(diffs)} differences):\n"
                f"NOTE: This baseline was generated by pure3270, not s3270.\n"
                f"If this is a genuine improvement in parsing, update the baseline:\n"
                f"  cp tests/data/screens/{trace_name.replace('.trc', '.screen.bin')} "
                f"tests/data/screens/{trace_name.replace('.trc', '.screen.bin')}.bak\n"
                f'  python -c "...generate new baseline..."\n'
                f"\nDifferences:\n{diff_summary}"
            )


class TestScreenContentRegression:
    """
    Validate specific screen content strings haven't changed.

    These tests catch regressions where the overall screen is mostly correct
    but specific fields have wrong values.

    Note: These tests use login.trc which is from a mock server (localhost:4001),
    not pub400.com. The "Global Payments Europe" content is from the test/mock
    environment, not the real pub400.com login screen.
    """

    @pytest.fixture(scope="class")
    def login_buffer(self):
        trace_path = TRACE_DIR / "login.trc"
        if not trace_path.exists():
            pytest.skip("login.trc not found")
        screen = parse_trace_to_buffer(str(trace_path))
        return bytes(screen.buffer), screen.to_text()

    def test_login_line0_system_title(self, login_buffer):
        """Line 0 must contain the system title."""
        _, text = login_buffer
        line0 = text.split("\n")[0]
        assert (
            "Global Payments" in line0 or "CMS/MMS" in line0
        ), f"System title missing from line 0: {line0!r}"

    def test_login_line1_user_field(self, login_buffer):
        """Line 1 must contain the username field label."""
        _, text = login_buffer
        line1 = text.split("\n")[1]
        assert (
            "Uzivatel" in line1 or "User" in line1
        ), f"Username field missing from line 1: {line1!r}"

    def test_login_line2_password_field(self, login_buffer):
        """Line 2 must contain the password field label."""
        _, text = login_buffer
        line2 = text.split("\n")[2]
        assert (
            "Heslo" in line2 or "Password" in line2
        ), f"Password field missing from line 2: {line2!r}"

    def test_login_line8_copyright(self, login_buffer):
        """Line 8 must contain the IBM copyright notice."""
        _, text = login_buffer
        line8 = text.split("\n")[8]
        assert (
            "COPYRIGHT" in line8.upper() and "IBM" in line8.upper()
        ), f"Copyright missing from line 8: {line8!r}"

    def test_login_buffer_first_byte(self, login_buffer):
        """First screen byte must be consistent."""
        actual_buffer, _ = login_buffer
        # The first byte should be a specific EBCDIC character from the login screen
        assert actual_buffer[0] != 0x00, "First byte is null - screen not populated"

    def test_login_buffer_ebcdic_encoding(self, login_buffer):
        """Screen buffer bytes should be valid EBCDIC, not raw ASCII."""
        actual_buffer, _ = login_buffer
        # Count bytes that look like EBCDIC (>0x7F range typical for EBCDIC letters)
        ebcdic_bytes = sum(1 for b in actual_buffer if b > 0x7F or b == 0x40)
        # Login screen should have significant EBCDIC content
        assert (
            ebcdic_bytes > 100
        ), f"Only {ebcdic_bytes} EBCDIC bytes found - screen may be in wrong encoding"
