# Pre-commit hooks for Pure3270
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # General hooks for basic file quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Code formatting
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        types: [python]

  # Import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        types: [python]

  # Style guide enforcement
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        types: [python]

  # Documentation quality
  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
        files: ^docs/.*\.(rst|md)$

  # Static analysis (mypy, pylint, bandit)
  - repo: local
    hooks:
      - id: static-analysis
        name: Run Static Analysis
        entry: run_static_analysis.py
        language: system
        files: \.py$
        pass_filenames: false
