name: Enhanced Copilot Regression Assistance

on:
  issues:
    types: [labeled, unlabeled]
  issue_comment:
    types: [created]

jobs:
  copilot-assistance:
    if: contains(github.event.issue.labels.*.name, 'regression') && contains(github.event.issue.labels.*.name, 'python-version')
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Copilot analysis
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue = context.payload.issue;
          
          // Check if issue has been labeled for Copilot assistance
          const hasCopilotLabel = issue.labels.some(label => 
            label.name === 'copilot-assist' || label.name === 'needs-ai-analysis'
          );
          
          if (hasCopilotLabel || context.event_name === 'issues') {
            const copilotPrompt = `
            @copilot[task] Please analyze this Python version regression issue and provide:
            
            1. **Root Cause Analysis**: What specific Python ${issue.title.match(/Python ([0-9.]+)/)?.[1] || 'version'} changes are causing the failure?
            2. **Code Examples**: Show the exact code changes needed to fix compatibility
            3. **Testing Strategy**: How to verify the fix works with both old and new Python versions
            4. **Risk Assessment**: Any potential side effects of the proposed changes
            5. **Implementation Priority**: Which files should be fixed first based on impact
            
            Focus on:
            - Syntax compatibility issues
            - Standard library API changes  
            - Asyncio behavior differences
            - Type hinting compatibility
            - String/encoding handling changes
            `;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: copilotPrompt
            });
          }