name: Python Release Monitor

on:
  schedule:
    # Check for new Python releases daily at 8 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-python-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Check for new Python releases
      id: check_releases
      run: |
        cd ${{ github.workspace }}
        python scripts/check_python_releases.py
        
        # Capture any changes made to workflow files
        if git diff --quiet .github/workflows/; then
          echo "no_changes=true" >> $GITHUB_OUTPUT
        else
          echo "no_changes=false" >> $GITHUB_OUTPUT
          echo "changed_files=$(git diff --name-only .github/workflows/)" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.check_releases.outputs.no_changes == 'false'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/workflows/
        git commit -m "Auto-update Python version matrix with new releases" -m "Updated by python-release-monitor workflow"
        git push

    - name: Create issue for manual review
      if: steps.check_releases.outputs.no_changes == 'false'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const changedFiles = '${{ steps.check_releases.outputs.changed_files }}';
          
          const issueTitle = 'Python Version Matrix Updated - Manual Review Required';
          const issueBody = `
          ## Python Version Matrix Updated

          The automated Python release monitor has detected new Python versions and updated the testing matrix.

          ### Changes Made
          \`\`\`
          ${changedFiles}
          \`\`\`

          ### Action Items
          - [ ] Review the updated CI workflow files
          - [ ] Verify compatibility with new Python versions
          - [ ] Update pyproject.toml classifiers if needed
          - [ ] Update documentation
          - [ ] Consider deprecating older versions if needed

          ### Next Steps
          Please review the changes and ensure the new Python versions are properly tested.
          The workflow files have been automatically updated but may need manual adjustments.
          
          _This issue was created automatically by the python-release-monitor workflow._
          `;

          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: issueTitle,
            body: issueBody,
            labels: ['python-version', 'maintenance', 'auto-generated']
          });
